### ISSUE TITLE
Output file is empty

### ISSUE THREAD

**Issue by dausruddin** [Tsur/vtt-to-srt#3]
`vtt-to-srt eng.vtt eng.srt`

This produced an empty eng.srt

**Comment by tsur** [comment]
Hi, sorry for not getting back to you sooner and thanks for reporting.

it would be very helpful if you could share your `eng.vtt` file, if possible, or the output you get back if any . Did you check it is a [valid](https://quuz.org/webvtt/) WebVTT file?

thanks

**Comment by dausruddin** [comment]
Hi, sorry for late reply too. 
I am far away from pc right now, plus the file I was trying to convert was deleted. 
I'll report back if I stumbled on the same issue.
Thanks
